src/Entity/CV.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CVRepository")
 */
class CV
{

    static $ages = [
        0 => 'Less than 18',
        1 => 'From 18 to 29',
        2 => '30 and more'
    ];

    static $levels = [
        1 => '10+',
        2 => '20+',
        3 => '30+',
        4 => '40+',
        5 => '50+',
        6 => '60+',
        7 => '70+',
        8 => '80+',
        9 => '90+',
        10 => '100+'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $region;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CharClass")
     * @ORM\JoinColumn(nullable=false)
     */
    private $charClass;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $twins;

    /**
     * @ORM\Column(type="boolean")
     */
    private $gvgExperience;

    /**
     * @ORM\Column(type="text")
     */
    private $previousExits;

    /**
     * @ORM\Column(type="text")
     */
    private $ourReasons;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $guarantors;

    /**
     * @ORM\Column(type="boolean")
     */
    private $confirmStatement;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="CVs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CharSide")
     * @ORM\JoinColumn(nullable=false)
     */
    private $charSide;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created;

    /**
     * @ORM\Column(type="boolean")
     */
    private $accepted = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $closed = false;

    /**
     * @ORM\Column(type="integer")
     */
    private $level;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CVvote", mappedBy="cv", orphanRemoval=true)
     */
    private $votes;

    public function __construct()
    {
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function getAgeText(): ?string {
        return self::$ages[$this->age];
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(?string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getCharClass(): ?CharClass
    {
        return $this->charClass;
    }

    public function setCharClass(?CharClass $charClass): self
    {
        $this->charClass = $charClass;

        return $this;
    }


    public function getTwins(): ?string
    {
        return $this->twins;
    }

    public function setTwins(?string $twins): self
    {
        $this->twins = $twins;

        return $this;
    }

    public function getGvgExperience(): ?bool
    {
        return $this->gvgExperience;
    }

    public function setGvgExperience(bool $gvgExperience): self
    {
        $this->gvgExperience = $gvgExperience;

        return $this;
    }

    public function getPreviousExits(): ?string
    {
        return $this->previousExits;
    }

    public function setPreviousExits(string $previousExits): self
    {
        $this->previousExits = $previousExits;

        return $this;
    }

    public function getOurReasons(): ?string
    {
        return $this->ourReasons;
    }

    public function setOurReasons(string $ourReasons): self
    {
        $this->ourReasons = $ourReasons;

        return $this;
    }

    public function getGuarantors(): ?string
    {
        return $this->guarantors;
    }

    public function setGuarantors(?string $guarantors): self
    {
        $this->guarantors = $guarantors;

        return $this;
    }

    public function getConfirmStatement(): ?bool
    {
        return $this->confirmStatement;
    }

    public function setConfirmStatement(bool $confirmStatement): self
    {
        $this->confirmStatement = $confirmStatement;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCharSide(): ?CharSide
    {
        return $this->charSide;
    }

    public function setCharSide(?CharSide $charSide): self
    {
        $this->charSide = $charSide;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(?\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getAccepted(): ?bool
    {
        return $this->accepted;
    }
    public function isAccepted(): ?bool
    {
        return ($this->accepted && $this->closed);
    }
    public function isDeclined(): ?bool
    {
        return (!$this->accepted && $this->closed);
    }
    public function isProcessing(): ?bool
    {
        return !$this->closed;
    }

    public function setAccepted(bool $accepted): self
    {
        $this->accepted = $accepted;

        return $this;
    }

    public function getClosed(): ?bool
    {
        return $this->closed;
    }

    public function setClosed(bool $closed): self
    {
        $this->closed = $closed;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }
    public function getLevelText(): ?string {
        return self::$levels[$this->level];
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    /**
     * @return Collection|CVvote[]
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(CVvote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
            $vote->setCv($this);
        }

        return $this;
    }

    public function removeVote(CVvote $vote): self
    {
        if ($this->votes->contains($vote)) {
            $this->votes->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getCv() === $this) {
                $vote->setCv(null);
            }
        }

        return $this;
    }
}

src/Form/CVType.php
<?php

namespace App\Form;

use App\Entity\CharClass;
use App\Entity\CharSide;
use App\Entity\CV;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CVType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('charClass', EntityType::class, [
                'class' => CharClass::class,
                'choice_label' => 'name',
                'choice_translation_domain' => 'messages',
            ])
            ->add('charSide', EntityType::class, [
                'label' => 'Side',
                'class' => CharSide::class,
                'choice_label' => 'name',
                'choice_translation_domain' => 'messages',
            ])
            ->add('level', ChoiceType::class, [
                'label' => 'Char level',
                'choices' => CV::$levels,
                'attr' => [
                    'placeholder' => 'Char level'
                ]
            ])
            ->add('age', ChoiceType::class, [
                'choices' => [
                    'Less than 18' => 0,
                    'From 18 to 29' => 1,
                    '30 and more' => 2
                ],
            ])
            ->add('region', TextType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => "Country / City"
                ]
            ])
            ->add('twins', TextType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => "Twins",
                ],
                'help' => "twins_help"
            ])
            ->add('gvgExperience', CheckboxType::class, ['label' => 'GVG Experience', 'required' => false])
            ->add('previousExits', TextareaType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => "Previous guilds",
                ],
                'help' => "previous_guilds_help"
            ])
            ->add('ourReasons', TextareaType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => "Reasons",
                ],
            ])
            ->add('guarantors', TextareaType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => "Guarantors",
                ],
                'help' => "guarantors_help"
            ])
            ->add('confirmStatement', CheckboxType::class, ['label' => 'Confirm Statement'])
            ->add('save', SubmitType::class, ['label' => 'Send', 'attr' => ['class' => 'btn-primary']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CV::class,
        ]);
    }
}

src/Controller/CVController.php
<?php

namespace App\Controller;

use App\Entity\CV;
use App\Entity\CVvote;
use App\Entity\User;
use App\Form\CVType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CVController extends AbstractController
{
    /**
     * @Route("/cv/finalaccept/{id}", name="cv_final_accept", requirements={"id"="\d+"})
     */
    public function cvFinalAccept(CV $cv) {
        return $this->closeVote($cv, true);
    }

    /**
     * @Route("/cv/finaldecline/{id}", name="cv_final_decline", requirements={"id"="\d+"})
     */
    public function cvFinalDecline(CV $cv) {
        return $this->closeVote($cv, false);
    }

    private function closeVote(CV $cv, $accepted) {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $em = $this->getDoctrine()->getManager();
        $cv->setAccepted($accepted);
        $cv->setClosed(true);
        $user = $cv->getUser();
        $user->setCharClass($cv->getCharClass());
        $user->setCharSide($cv->getCharSide());
        $em->persist($cv);
        $em->persist($user);
        $em->flush();
        $this->addFlash('success', "Заявка закрыта");
        return $this->redirectToRoute('cv_list');
    }

    /**
     * @Route("/cv/accept/{id}", name="cv_accept", requirements={"id"="\d+"})
     */
    public function cvAccept(CV $cv) {
        return $this->proccessVote($cv, true);
    }

    /**
     * @Route("/cv/decline/{id}", name="cv_decline", requirements={"id"="\d+"})
     */
    public function cvDecline(CV $cv) {
        return $this->proccessVote($cv, false);
    }

    private function proccessVote(CV $cv, bool $accepted=false) {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $vote = new CVvote();
        $vote->setAccepted($accepted);
        $vote->setUser($this->getUser());
        $vote->setCv($cv);
        $vote->setCreated(new \DateTime());
        $em = $this->getDoctrine()->getManager();
        $em->persist($vote);
        $em->flush();
        $this->addFlash("success", "Ваше мнение принято");
        return $this->redirectToRoute('cv_view', ['id' => $cv->getId()]);
    }

        /**
     * @Route("/cv/{id}", name="cv_view", requirements={"id"="\d+"})
     */
    public function cvView(CV $cv) {
        if (!$cv) {
            $this->addFlash('danger', "Error");
            return $this->redirectToRoute("cv_list");
        }

        // check user already voted this CV
        $vote_rep = $this->getDoctrine()->getRepository('App:CVvote');
        $user_vote = $vote_rep->findOneBy(['user' => $this->getUser(), 'cv' => $cv]);

        // count votes
        $positive = $vote_rep->count(['accepted' => true, 'cv' => $cv]);
        $negative = $vote_rep->count(['accepted' => false, 'cv' => $cv]);

        return $this->render('cv/view.html.twig', [
            'cv' => $cv,
            'voted' => $user_vote?true:false,
            'positive' => $positive,
            'negative' => $negative,
        ]);
    }


    /**
     * @Route("/cv", name="cv_list")
     */
    public function cvList(Request $request, PaginatorInterface $paginator) {
        $rep = $this->getDoctrine()->getRepository('App:CV');

        $cvs = $rep->findPaginated();
        $pagination = $paginator->paginate(
            $cvs,
            $request->query->getInt('page', 1),
            20
        );

        return $this->render('cv/list.html.twig', [
            'cvs' => $pagination
        ]);
    }


    /**
     * @Route("/cv/apply", name="cv_apply")
     */
    public function cvApply(Request $request)
    {
        if ($this->isGranted('ROLE_USER')) {
            return $this->redirectToRoute('cv_list');
        }
        $this->denyAccessUnlessGranted('ROLE_GUEST');

        /** @var User $user */
        $user = $this->getUser();
        foreach ($user->getCVs() as $cv) {
            if ($user->getUserRole()->getRole() == 'ROLE_GUEST' && ($cv->isProcessing() || $cv->isAccepted())) {
                //$this->addFlash('danger', 'You are already have processing application');
                return $this->redirectToRoute('cv_list');
            }
        }

        $cv = new CV();
        $cv->setUser($this->getUser());
        $cv->setCreated(new \DateTime());

        $form = $this->createForm(CVType::class, $cv);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($cv);
            $em->flush();
            $this->addFlash('success', 'Application send for approvement');
            return $this->redirectToRoute('homepage');
        }

        return $this->render('cv/application.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/cv/application.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Guild application{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12 col-md-5 col-lg-6">
            <h1>{% trans %}Player application{% endtrans %}</h1>
            {{ form_start(form) }}
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}

templates/cv/list.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{% trans %}CV list{% endtrans %} {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <h1>{% trans %}CV list{% endtrans %}</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">{% trans %}Nickname{% endtrans %}</th>
                    <th scope="col">{% trans %}Char class{% endtrans %}</th>
                    <th scope="col">{% trans %}Side{% endtrans %}</th>
                    <th scope="col">{% trans %}Char level{% endtrans %}</th>
                    <th scope="col">{% trans %}Real name{% endtrans %}</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                {% if cvs is defined %}
                <tbody>
                {% for cv in cvs %}
                <tr class="">
                    <th scope="row"><a href="{{ path('cv_view', {'id': cv.id}) }}">{{ cv.user.nickName }}</a></th>
                    <td>{{ cv.charClass.name|trans }}</td>
                    <td>{{ cv.charSide.name|trans }}</td>
                    <td>{{ cv.leveltext }}</td>
                    <td>{{ cv.user.realName }}</td>
                    <td>
                        {% if cv.accepted %}
                            <span class="badge badge-success text-white">Принят</span>
                        {% elseif cv.declined %}
                            <span class="badge badge-danger text-white">Отказ</span>
                        {% else %}
                            <span class="badge badge-warning">В процессе</span>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>
    </div>
{% endblock %}


{% block javascripts %}
{{ parent() }}
{% endblock %}

templates/cv/view.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{% trans %}CV list{% endtrans %} {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <span class="badge badge-pill">{{ cv.created|date('d/m/Y, H:i') }}</span>
                {% if cv.accepted %}
                    <span class="badge badge-success text-white">Принят</span>
                {% elseif cv.declined %}
                    <span class="badge badge-danger text-white">Отказ</span>
                {% else %}
                    <span class="badge badge-warning">В процессе</span>
                {% endif %}
                <span class="badge badge-success">{{ positive }}</span>
                <span class="badge badge-danger">{{ negative }}</span>

            </div>
            <h1>{% trans %}CV{% endtrans %} <small>{{ cv.user.nickName }}</small></h1>
            {% if cv.accepted and cv.user == app.user %}
                <p class="lead text-success">Ваша заявка утверждена! Пожалуйста, обратитесь в игре к офицерам для принятия в клан.</p>
            {% endif %}
            <table class="table table-sm">
                <tr>
                    <td>{% trans %}Nickname{% endtrans %}</td>
                    <td class="font-weight-bold">{{ cv.user.nickName }}</td>
                </tr>
                <tr>
                    <td>{% trans %}Char class{% endtrans %} / {% trans %}Level{% endtrans %} / {% trans %}Side{% endtrans %}</td>
                    <td class="font-weight-bold">{{ cv.charClass.name|trans }} / {{ cv.levelText }} / {{ cv.charSide.name|trans }}</td>
                </tr>
                <tr>
                    <td>{% trans %}Real name{% endtrans %}, {% trans %}Age{% endtrans %}</td>
                    <td class="font-weight-bold">{{ cv.user.realName }}, {{ cv.ageText|trans }}</td>
                </tr>
                <tr>
                    <td>{% trans %}Country / City{% endtrans %}</td>
                    <td class="font-weight-bold">{{ cv.region }}</td>
                </tr>
                <tr>
                    <td>{% trans %}GVG Experience{% endtrans %}</td>
                    <td>{% if cv.gvgExperience %}<i class="oi oi-check text-success"></i>{% else %}<i class="oi oi-x text-danger"></i>{% endif %}</td>
                </tr>
                <tr>
                    <td>{% trans %}twins_help{% endtrans %}</td>
                    <td class="font-weight-bold">{{ cv.twins }}</td>
                </tr>
                <tr>
                    <td>{% trans %}previous_guilds_help{% endtrans %}</td>
                    <td class="font-weight-bold">{{ cv.previousExits }}</td>
                </tr>
                <tr>
                    <td>{% trans %}Reasons{% endtrans %}</td>
                    <td class="font-weight-bold">{{ cv.ourReasons }}</td>
                </tr>
                <tr>
                    <td>{% trans %}Guarantors{% endtrans %}</td>
                    <td class="font-weight-bold">{{ cv.guarantors }}</td>
                </tr>
                <tr>
                    <td class="text-right text-muted pt-3">
                        {% if is_granted('ROLE_GENERAL') and not cv.closed %}
                            <a href="{{ path('cv_final_decline', {'id': cv.id}) }}" class="btn btn-danger">{% trans %}Закрыть и отклонить{% endtrans %}</a>
                            <a href="{{ path('cv_final_accept', {'id': cv.id}) }}" class="btn btn-success">{% trans %}Закрыть и утвердить{% endtrans %}</a>
                        {% endif %}
                    </td>
                    <td class="pt-3">
                        {% if is_granted('ROLE_USER') and not voted and not is_granted('ROLE_GENERAL') %}
                        <a href="{{ path('cv_accept', {'id': cv.id}) }}" class="btn btn-success">{% trans %}Accept{% endtrans %}</a>
                        <a href="{{ path('cv_decline', {'id': cv.id}) }}" class="btn btn-danger">{% trans %}Decline{% endtrans %}</a>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}


{% block javascripts %}
{{ parent() }}
{% endblock %}